Repository ontohub/hets-agent, pull requests merged in 2018-02, with the labels that each got.

#60 Fix queue vhost
  .gitignore
  lib/hets-agent/worker.rb
Labels: ready for review

#61 Use bunny publish instead of sneakers
  lib/hets-agent/worker.rb
  spec/lib/worker_spec.rb
  spec/spec_helper.rb
Labels: ready for review

#62 Accept and pass args in constructor
  lib/hets-agent/worker.rb
Labels: in progress

#63 Dont cache rabbitmq connections
  lib/hets-agent/worker.rb
Labels: in progress

#64 Simplify rubocop config.
  .rubocop.yml
  .rubocop_disabled.yml
  .rubocop_enabled.yml
  .rubocop_modified.yml
  lib/hets-agent.rb
  spec/support/bunnymock_recent_history_exchange.rb
Labels: approved

#65 Add settings validation, rename executable
  README.md
  bin/hets-agent
  config/settings.yml
  config/settings/test.yml
  config/settings_validation_errors.yml
  lib/hets-agent/application.rb
  lib/hets-agent/settings_schema.rb
  spec/lib/settings_schema_spec.rb
  spec/support/hets
Labels: in progress

#66 Update readme with new rabbitmq:send_hets_version task
  README.md
Labels: ready for review
